<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Story;

class ResetDraftVisuals extends Command
{
    protected $signature = 'story:reset-visuals {--all : Reset ALL draft stories} {--id= : specific story ID}';
    protected $description = 'Resets visuals of draft stories to placeholders so they can be regenerated by the worker';

    public function handle()
    {
        $id = $this->option('id');
        $all = $this->option('all');
        
        $query = Story::whereIn('durum', ['taslak', 'draft', 'Taslak', 'Draft']);
        
        if ($id) {
            $query->where('id', $id);
        } elseif (!$all) {
            $this->error("Please specify --id=X or --all");
            return;
        }

        $stories = $query->get();
        $this->info("Found " . $stories->count() . " stories to reset.");
        
        $placeholderUrl = "https://placehold.co/1280x720/1f2937/00ff00?text=Generating+Visuals...";

        foreach ($stories as $story) {
            $this->info("Resetting Story ID: {$story->id}");
            
            // Regex to find ANY img tag in the scene containers and replace source
            // We assume structure matches standard generator output
            // But to be safe, we just look for scene imgs
            // Or simpler: We assumed scene structure is standard. 
            // If the user manually edited, regex might be risky. 
            // BUT user said "I save as draft".
            // Let's replace ANY img src that looks like a story image (or just all images in scene-container?)
            
            // Actually, simply replacing the IMG tag with the Placeholder IMG tag is cleaner
            // Pattern: <img ... src="..." ... alt="Scene X" ...>
            // We want to reset it to: <img src="$placeholderUrl" alt="Scene X" ...>
            
            $story->metin = preg_replace_callback(
                '/<img[^>]+alt=[\'"]Scene (\d+)[\'"][^>]*>/i',
                function ($matches) use ($placeholderUrl) {
                    $index = $matches[1];
                    return "<img src='$placeholderUrl' alt='Scene $index' class='w-full rounded shadow-lg border-2 border-gray-800 hover:border-purple-500 transition duration-500'>";
                },
                $story->metin
            );
            
            $story->save();
            $this->info("Story {$story->id} visuals reset to placeholders.");
        }
        
        $this->info("All done! Worker will now pick these up.");
    }
}
